language: cpp

matrix:
  - os: linux
    compiler: gcc
    script:
      - mkdir -p build && cd build
      - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_BUILD_TYPE=RELEASE -L ../
      - make
    
    env:
      - COMPILER=g++-5
  
